-- EGAutoNews — banco novo e vazio
-- Execute uma única vez no SQL Editor de um projeto Supabase NOVO.
-- Este arquivo cria somente estrutura. Nenhum dado antigo é copiado.

begin;

-- 1) Empresas automotivas cadastradas pelo formulário público.
create table if not exists public.stall_registrations (
  id bigint generated by default as identity primary key,
  full_name text not null,
  cpf_cnpj text not null,
  document_type text not null default 'cnpj' check (document_type = 'cnpj'),
  email text not null,
  phone text not null,
  business_name text not null,
  region text not null,
  category text not null check (category in ('Agência veicular', 'Autopeças', 'Oficina', 'Outras')),
  booth_location text,
  cep text,
  description text not null,
  days_hours text,
  consent_given integer not null default 1,
  status text not null default 'received' check (status in ('received', 'reviewing', 'approved', 'rejected')),
  photo_url text,
  logo_url text,
  public_description text,
  public_ready boolean not null default false,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stall_registrations_cnpj_digits_check
    check (regexp_replace(cpf_cnpj, '[^0-9]', '', 'g') ~ '^[0-9]{14}$')
);

create index if not exists stall_registrations_status_idx
  on public.stall_registrations(status);
create index if not exists stall_registrations_category_idx
  on public.stall_registrations(category);
create index if not exists stall_registrations_public_ready_idx
  on public.stall_registrations(status, public_ready, category);
create index if not exists stall_registrations_featured_idx
  on public.stall_registrations(is_featured, status, public_ready);

alter table public.stall_registrations enable row level security;

-- 2) Usuários do painel administrativo.
create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;

-- 3) Feiras usadas na Home e no painel.
create table if not exists public.fairs (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  region text not null,
  address text,
  cep text,
  days_hours text,
  contact_name text,
  contact_phone text,
  contact_email text,
  photo_url text,
  is_featured boolean not null default false,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists fairs_status_idx on public.fairs(status);
create index if not exists fairs_featured_status_idx on public.fairs(is_featured, status);
alter table public.fairs enable row level security;

-- 4) Notícias do portal.
create table if not exists public.news_articles (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  category text not null default 'EGAutoNews',
  author text not null default 'Redação',
  location text not null default 'Distrito Federal',
  excerpt text,
  content text not null,
  image_url text,
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists news_articles_status_idx on public.news_articles(status);
create index if not exists news_articles_published_at_idx on public.news_articles(published_at desc);
create index if not exists news_articles_category_idx on public.news_articles(category);
alter table public.news_articles enable row level security;

drop policy if exists news_articles_public_read on public.news_articles;
create policy news_articles_public_read on public.news_articles
  for select using (status = 'published' and (published_at is null or published_at <= now()));

-- 5) Publicidade administrada pelo painel.
create table if not exists public.sponsor_banners (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text not null,
  target_url text,
  status text not null default 'inactive' check (status in ('active', 'inactive')),
  display_order integer not null default 0,
  starts_at timestamptz,
  ends_at timestamptz,
  placement text not null default 'home_bottom',
  campaign_group text not null default 'default',
  display_mode text not null default 'fixed' check (display_mode in ('fixed', 'split', 'rotation')),
  rotation_seconds integer not null default 8 check (rotation_seconds >= 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists sponsor_banners_status_idx on public.sponsor_banners(status);
create index if not exists sponsor_banners_placement_idx on public.sponsor_banners(placement);
create index if not exists sponsor_banners_group_idx on public.sponsor_banners(campaign_group);
alter table public.sponsor_banners enable row level security;

drop policy if exists sponsor_banners_public_read on public.sponsor_banners;
create policy sponsor_banners_public_read on public.sponsor_banners
  for select using (
    status = 'active'
    and (starts_at is null or starts_at <= now())
    and (ends_at is null or ends_at >= now())
  );

-- 6) Buckets públicos usados pelos servidores; os uploads são feitos com a chave server-side.
insert into storage.buckets (id, name, public) values
  ('stall-assets', 'stall-assets', true),
  ('fairs', 'fairs', true),
  ('news', 'news', true),
  ('sponsors', 'sponsors', true)
on conflict (id) do update set public = true;

commit;

-- Depois de executar este SQL:
-- 1. Gere localmente a senha do Admin: npm run admin:hash -- egautonews2026
-- 2. Copie o hash gerado.
-- 3. Rode este comando trocando COLE_O_HASH_AQUI pelo valor gerado:
-- insert into public.admin_users (username, password_hash, active)
-- values ('admin', 'COLE_O_HASH_AQUI', true);
